version: '3.3'
volumes:
  data-volume: {}
services:
  weather_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: 'weather'
      MYSQL_USER: 'master'
      MYSQL_PASSWORD: 'RjP79Aaj7dfV'
      MYSQL_ROOT_PASSWORD: 'RjP79Aaj7dfV'
    ports:
      - '3311:3306'
    expose:
      - '3306'
